### ISSUE TITLE
关闭弹窗问题

### ISSUE THREAD

**Issue by 18335180686** [bytedance/flutter_ume#10]
如果使用flutter_ume_kit_console，系统的弹窗无法通过代码关闭。也会到这awesome_dialog这个插件的关闭失效。请问怎么解决？

**Comment by talisk** [comment]
> 如果使用flutter_ume_kit_console，系统的弹窗无法通过代码关闭。也会到这awesome_dialog这个插件的关闭失效。请问怎么解决？

请问系统弹窗是指什么？`awesome_dialog` 插件使用的是什么版本？可以提供下更详细的信息吗

**Comment by smileShirely** [comment]
> 如果使用flutter_ume_kit_console，系统的弹窗无法通过代码关闭。也会到这awesome_dialog这个插件的关闭失效。请问怎么解决？

@18335180686 你好，请问系统弹窗指的是什么？使用的 `awesome_dialog` 的版本是什么？“使用 flutter_ume_kit_console”是指打开了插件面板还是只要引入了就会出现这样的现象？

**Comment by XiubinChen** [comment]
@smileShirely  我的项目上使用了getx   通过调用Get.dialog 打开会话窗口   发现引入flutter_ume 之后 调用 Get.back  导致会话窗口关闭失败。

**Comment by 18335180686** [comment]
> > 如果使用flutter_ume_kit_console，系统的弹窗无法通过代码关闭。也会到这个插件的关闭对话框失效_这请问怎么解决？
> 
> @18335180686你好，请问系统弹窗是什么？使用的`awesome_dialog`版本是什么？“使用flutter_ume_kit_console”是指打开了面板还是只要出现了就会出现这样的现象？

awesome_dialog是2.1.0版本；在任何情况下，关闭awesome_dialog弹窗都是失效的。

flutter环境如下
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/tutu/Documents/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

**Comment by smileShirely** [comment]
#13 Merged.

修改 pubspec.yaml 中内容：
``` yaml
dependency_overrides:
  flutter_ume:
    git: https://github.com/bytedance/flutter_ume.git
    ref: develop_nullsafety
```

@XiubinChen @18335180686 试一下？

**Comment by smileShirely** [comment]
Same with #6 , closed.

**Comment by 18335180686** [comment]
这个问题还是没有得到解决
