### ISSUE TITLE
UME Support for Dio 5+ 

### ISSUE THREAD

**Issue by RohanDoshi21** [bytedance/flutter_ume#114]
## Use case 建议
Update `flutter_ume_kit_dio` to support latest version of `dio` (5.0.0)

## Scenes 使用场景

Because every version of `flutter_ume_kit_dio` depends on `dio ^4.0.0` and blazepod depends on `dio ^5.1.2`, `flutter_ume_kit_dio`is `forbidden`.
So, because blazepod depends on `flutter_ume_kit_dio ^1.0.0`

**Comment by mdddj** [comment]
```yaml
flutter_ume_kit_dio_plus: ^2.0.0
```
