### ISSUE TITLE
能否让flutter_ume_kit_dio 适配dio5 api

### ISSUE THREAD

**Issue by persenzhou** [bytedance/flutter_ume#121]
## Use case 建议
建议适配dio5的api，目前项目已经使用了dio5,导致集成ume api冲突，谢谢

## dependencies
dependencies:
  flutter:
    sdk: flutter
   dio: 5.1.0

**Comment by mdddj** [comment]
试下我这个
```yaml
flutter_ume_kit_dio_plus: ^2.0.0
```

**Comment by persenzhou** [comment]
use this flutter_ume_kit_dio_plus: ^2.0.0
