### ISSUE TITLE
关闭弹窗失效问题

### ISSUE THREAD

**Issue by 18335180686** [bytedance/flutter_ume#17]
https://github.com/bytedance/flutter_ume/issues/10#issue-958766632

这个问题还是存在

 flutter_ume:
    dependency: transitive
    description:
      name: flutter_ume
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0-dev.0"
  flutter_ume_kit_console:
    dependency: "direct dev"
    description:
      name: flutter_ume_kit_console
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0-dev.0"

这个是弹窗插件版本
awesome_dialog:
    dependency: "direct dev"
    description:
      name: awesome_dialog
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"

https://user-images.githubusercontent.com/19197536/128666517-786d7032-7386-440c-b45b-3eafc98bb7ca.mp4

**Comment by talisk** [comment]
@18335180686 
#13 合入的`develop_nullsafety` 分支，需要你使用 git 依赖。

``` yaml
dependency_overrides:
  flutter_ume:
    git: https://github.com/bytedance/flutter_ume.git
    ref: develop_nullsafety
```

目前看你贴的应该是使用的 pub 依赖？方便检查一下 `pubspec.yaml` 文件吗？

**Comment by smileShirely** [comment]
@18335180686 
#13 合入的`develop_nullsafety` 分支，需要你使用 git 依赖。

``` yaml
dependency_overrides:
  flutter_ume:
    git: https://github.com/bytedance/flutter_ume.git
    ref: develop_nullsafety
```

目前看你贴的应该是使用的 pub 依赖？方便检查一下 `pubspec.yaml` 文件吗？

**Comment by 18335180686** [comment]
https://github.com/bytedance/flutter_ume/issues/17#issuecomment-894993258
flutter_ume_kit_console，这个插件是不是也得改成git的地址啊？
<img width="566" alt="WeChata15dd6adf952928c8f5c0ae52317c7ca" src="https://user-images.githubusercontent.com/19197536/128669831-874fa835-8974-4330-a4fc-d9a7ef64914f.png">
<img width="428" alt="WeChat20a059b51164732153a9aba29637aab3" src="https://user-images.githubusercontent.com/19197536/128669848-53902e21-d7e5-4ddc-bc47-ec5afb089d19.png">

**Comment by talisk** [comment]
> [#17 (comment)](https://github.com/bytedance/flutter_ume/issues/17#issuecomment-894993258)
> flutter_ume_kit_console，这个插件是不是也得改成git的地址啊？
> <img alt="WeChata15dd6adf952928c8f5c0ae52317c7ca" width="566" src="https://user-images.githubusercontent.com/19197536/128669831-874fa835-8974-4330-a4fc-d9a7ef64914f.png">
> <img alt="WeChat20a059b51164732153a9aba29637aab3" width="428" src="https://user-images.githubusercontent.com/19197536/128669848-53902e21-d7e5-4ddc-bc47-ec5afb089d19.png">

不需要的，override `flutter_ume` 就可以了

**Comment by smileShirely** [comment]
> [#17 (comment)](https://github.com/bytedance/flutter_ume/issues/17#issuecomment-894993258)
> flutter_ume_kit_console，这个插件是不是也得改成git的地址啊？
> <img alt="WeChata15dd6adf952928c8f5c0ae52317c7ca" width="566" src="https://user-images.githubusercontent.com/19197536/128669831-874fa835-8974-4330-a4fc-d9a7ef64914f.png">
> <img alt="WeChat20a059b51164732153a9aba29637aab3" width="428" src="https://user-images.githubusercontent.com/19197536/128669848-53902e21-d7e5-4ddc-bc47-ec5afb089d19.png">

不需要的，override `flutter_ume` 就可以了

**Comment by 18335180686** [comment]
https://github.com/bytedance/flutter_ume/issues/17#issuecomment-895143202
哦哦 那还是存在弹窗不能关闭的问题

**Comment by smileShirely** [comment]
> [#17 (comment)](https://github.com/bytedance/flutter_ume/issues/17#issuecomment-895143202)
> 哦哦 那还是存在弹窗不能关闭的问题

那方便提供下你打开弹窗/关闭弹窗的代码吗？我在 flutter_ume 的 example 工程中测试过使用 `awesome_dialog` 打开弹窗/关闭弹窗是正常的

**Comment by smileShirely** [comment]
@18335180686 在 flutter_ume 的 example 工程中，已经有使用 `awesome_dialog` 打开弹窗的例子了，你运行一下试试看？

**Comment by 18335180686** [comment]
> @18335180686 在 flutter_ume 的 example 工程中，已经有使用 `awesome_dialog` 打开弹窗的例子了，你运行一下试试看？

使用系统自带的dialog是好使的，使用awesome_dialog插件就不好使了，下面是系统和awesome_dialog插件的使用代码，视频是这两个dialog分别的表象。
--------------------------------------------------
    showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
              title: const Text('这条帖子将被永久删除，任何人都不会再看到这条帖子，包括你自己。是否继续？'),
              actions: <Widget>[
                TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: const Text('取消'))
              ],
            ),
        useRootNavigator: false);
    
 ------------------------------------------------   
    AwesomeDialog(
        context: context,
        animType: AnimType.BOTTOMSLIDE,
        headerAnimationLoop: true,
        dialogType: DialogType.INFO,
        body: dialogContent(content: "这条帖子将被永久删除，任何人都不会再看到这条帖子，包括你自己。是否继续？"),
        btnOkOnPress: () {

        },
        btnOkText: "取消",
        useRootNavigator: false)
      ..show();

https://user-images.githubusercontent.com/19197536/128801954-eeb23b88-f793-405e-baf9-88446c3187ae.mp4

**Comment by smileShirely** [comment]
https://user-images.githubusercontent.com/11439167/128817285-54ceba76-73bb-4c28-afd4-388da6c0c052.mp4


@18335180686 我在 example 工程中测试了同样的代码，是正常的。你更新了以来之后可能没有执行 flutter pub get？我将完整的 example 中的示例 push 到了本仓库的 `temp/test_for_issue17`， 你 clone 下本仓库，对照看下 example 有没有什么区别？

**Comment by smileShirely** [comment]
> [#17 (comment)](https://github.com/bytedance/flutter_ume/issues/17#issuecomment-894993258)
> flutter_ume_kit_console，这个插件是不是也得改成git的地址啊？
> <img alt="WeChata15dd6adf952928c8f5c0ae52317c7ca" width="566" src="https://user-images.githubusercontent.com/19197536/128669831-874fa835-8974-4330-a4fc-d9a7ef64914f.png">
> <img alt="WeChat20a059b51164732153a9aba29637aab3" width="428" src="https://user-images.githubusercontent.com/19197536/128669848-53902e21-d7e5-4ddc-bc47-ec5afb089d19.png">

``` yaml
dependency_overrides:
  flutter_ume:
    git:
      url: https://github.com/bytedance/flutter_ume.git
      ref: develop_nullsafety
```

另外之前这里写的有点问题，少加了一行 git:。原来的写法，pub get 是执行不过去的。

**Comment by 18335180686** [comment]
ok 好了 谢谢
