### ISSUE TITLE
手机上连接不到SocketException，查看不了代码

### ISSUE THREAD

**Issue by niezhiyang** [bytedance/flutter_ume#29]
[ERROR:flutter/lib/ui/ui_dart_state.cc(207)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 37830
E/flutter (25739): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
E/flutter (25739): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1679:26)
E/flutter (25739): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter (25739): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:1890:22)
E/flutter (25739): #4      Socket.startConnect (dart:io/socket.dart:738:21)
E/flutter (25739): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
E/flutter (25739): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805:12)
E/flutter (25739): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810:12)
E/flutter (25739): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:12)
E/flutter (25739): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
E/flutter (25739): #10     _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1027:24)
E/flutter (25739): #11     WebSocket.connect (dart:_http/websocket.dart:379:22)
E/flutter (25739): #12     vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)

**Comment by smileShirely** [comment]
@niezhiyang 请问你执行 flutter run 的时候是否添加了 `--disable-dds` flag 呢？请参考 README.md 文档-快速接入-第 5 步
