### ISSUE TITLE
与原生混合开发，需要Restart才能正常使用

### ISSUE THREAD

**Issue by AIYO77** [bytedance/flutter_ume#32]
## 与原生混合开发，需要进入flutter页面Restart才能正常使用

    通过flutter_boost混合开发，进入到flutter页面，需要restart才能正常使用

### Flutter doctor

    [✓] Flutter (Channel master, 2.6.0-1.0.pre.111, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-1.0.pre.111 at /Users/admin/Desktop/xw/flutter/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 965bd1ff40 (2 weeks ago), 2021-08-29 23:41:02 -0400
    • Engine revision f4a380f3e5
    • Dart version 2.15.0 (build 2.15.0-65.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

``` bash

```

### UME and kits version UME 及插件包版本

  flutter_ume: ^0.2.1
  flutter_ume_kit_ui: ^0.2.1 
  flutter_ume_kit_device: ^0.2.1  
  flutter_ume_kit_perf: ^0.2.1
  flutter_ume_kit_console: ^0.2.1
  flutter_ume_kit_dio: ^0.2.0 

``` bash

```

**Comment by smileShirely** [comment]
@masterxing 你好，我在 `flutter_boost` 的 demo 工程中测试接入了 `flutter_ume`，没有复现这个问题。方便提供下简单的 Demo 工程吗？

**Comment by cuocuo** [comment]
> @masterxing 你好，我在 `flutter_boost` 的 demo 工程中测试接入了 `flutter_ume`，没有复现这个问题。方便提供下简单的 Demo 工程吗？

和楼主出现一样的问题，单独跑flutter项目就可以。

**Comment by smileShirely** [comment]
> > @masterxing 你好，我在 `flutter_boost` 的 demo 工程中测试接入了 `flutter_ume`，没有复现这个问题。方便提供下简单的 Demo 工程吗？
> 
> 和楼主出现一样的问题，单独跑flutter项目就可以。

可以提供下 Demo 工程吗？

**Comment by zhongxuerui521** [comment]
混合开发的跑的时候，ToolBarWidget类在initState的时候windowSize.height获取到是0，屏幕高度获取不到，Restart后这个值就获取到了。这个值改为外层传递过来或者先写死一下就可以了。

**Comment by tanzhihao1qaz** [comment]
> 混合开发的跑的时候，ToolBarWidget类在initState的时候windowSize.height获取到是0，屏幕高度获取不到，Restart后这个值就获取到了。这个值改为外层传递过来或者先写死一下就可以了。

有个更快的处理方法，flutter_ume包下有个constants类，里面存着ratio和windowSize，这两个东西原本是直接定义成常量了。。。只要改成通过get方法获取就可以，如下：
`
double get ratio {
  return WidgetsBinding.instance!.window.devicePixelRatio;
}

Size get windowSize {
  return WidgetsBinding.instance!.window.physicalSize / ratio;
}
`
这样每次用他的时候才去计算，这肯定没错了
