### ISSUE TITLE
如何主动调用方法隐藏调试工具页面？

### ISSUE THREAD

**Issue by cuocuo** [bytedance/flutter_ume#35]
## 我希望能主动已经唤起的调试页面

请问如何通过调用代码隐藏当前的调试页面？

**Comment by smileShirely** [comment]
@cuocuo `enable` 传入 `false`就可以了

**Comment by cuocuo** [comment]
@smileShirely 你说的是初始化的时候，我指的是没一个独立的页面可以主动隐藏。

**Comment by smileShirely** [comment]
@cuocuo 可以参考下本仓库中示例工程中的代码：`example/lib/main.dart`
``` dart
runApp(MultiProvider(
  providers: [
    ChangeNotifierProvider(
      create: (_) => UMESwitch(),
    ),
  ],
  builder: (ctx, child) {
    return injectUMEWidget(
      child: MyApp(),
      enable: ctx.watch<UMESwitch>().enable,
    );
  },
));
```

这段代码示例使用了 [Provider](https://pub.dev/packages/provider) 进行状态管理，当点击 example 右上角的 icon 按钮后，将切换 `enable` 状态，移除 UME

**Comment by cuocuo** [comment]
@smileShirely 谢谢你详细的回答！这个就关闭了整个调试浮窗。而我的意思是调试浮窗点开之后我再点击某一个调试工具，然后在如何在这个页面点击了一个按钮就隐藏了这个单独的页面，并且回到了浮窗的初始状态。

**Comment by smileShirely** [comment]
@cuocuo 明白了你的意思。点开单个调试工具之后，圆形浮窗仍然在屏幕上，再次点击该浮窗即可关闭当前调试工具

**Comment by cuocuo** [comment]
> @cuocuo 明白了你的意思。点开单个调试工具之后，圆形浮窗仍然在屏幕上，再次点击该浮窗即可关闭当前调试工具

可以开放代码关闭吗？

**Comment by smileShirely** [comment]
@cuocuo 建议已采纳，近期改造

**Comment by cuocuo** [comment]
> 

你好！请问新版本有加入控制的代码吗？
