### ISSUE TITLE
别的项目根本依赖不了啊，一直报错，官方不解决下吗

### ISSUE THREAD

**Issue by zewsummer** [bytedance/flutter_ume#36]
## Steps to Reproduce 复现步骤

1. ... 
2. ... 
3. ... 

**Expected results 期望结果:** 

**Actual results 实际结果:** 

## Error log 错误日志

``` bash

```

### Flutter doctor

``` bash

```

### UME and kits version UME 及插件包版本

``` bash

```

**Comment by smileShirely** [comment]
@zewsummer 请具体描述下错误日志和环境信息
