### ISSUE TITLE
developer.log在Console上没有显示

### ISSUE THREAD

**Issue by 18335180686** [bytedance/flutter_ume#37]
import 'dart:developer' as developer;
 developer.log(
        "${DateTime.now().toString().substring(11)}->${judgeIcon(logType)} $data");

这种打印log的方法，在Android studio上不会吧log截断，官方告诉使用这个打印log的不会被截断。但是developer.log在Console上没有显示
![4611635410525_ pic](https://user-images.githubusercontent.com/19197536/139220140-7f611e86-1be5-4406-b1db-d45fd717d95d.jpg)

**Comment by 18335180686** [comment]
如果使用（logger: ^1.1.0）插件的话，在ume上也是不显示log的

**Comment by smileShirely** [comment]
@18335180686 目前 console 插件支持的是 `debugPrint` 输出的日志。其他日志输出形式暂不支持。想请问目前业务正在使用什么方式打印日志呢？

**Comment by AlexV525** [comment]
> 这种打印log的方法，在Android studio上不会吧log截断，官方告诉使用这个打印log的不会被截断。但是developer.log在Console上没有显示

`developer.log` 是一个 VM 上的方法，Dart 并没有提供重写的入口，只能在运行终端中查看。
