### ISSUE TITLE
构建release包或者profile包是否可以开启ume

### ISSUE THREAD

**Issue by a27919478** [bytedance/flutter_ume#39]
想着在flutter build apk是否支持如题目所说的那样

**Comment by smileShirely** [comment]
@a27919478  是可以在 `release` 和 `profile` mode 下使用 ume 的部分功能。但请一定要小心不要在生产环境中引入了 ume

**Comment by a27919478** [comment]
@smileShirely 现在我flutter build apk后，在真机安装APK点击图标，工具栏并没有显示

**Comment by a27919478** [comment]
![WechatIMG672](https://user-images.githubusercontent.com/19726808/141716363-83d70285-a2ab-40a9-b1e6-89937d106d42.jpeg)

**Comment by talisk** [comment]
> @smileShirely 现在我flutter build apk后，在真机安装APK点击图标，工具栏并没有显示

请贴一下接入代码

**Comment by a27919478** [comment]
![image](https://user-images.githubusercontent.com/19726808/142399282-f1ab8a68-c0f2-4947-82ba-b5773e7dc500.png)

**Comment by talisk** [comment]
代码中 `bool enableUme = kDebug;` 这个 kDebug 的值是什么呢？@a27919478

**Comment by a27919478** [comment]
这个只是我脚本设置的一个值，和这个没什么关系，因为如果为false那个flutter图标都不会显示。
我是使用构建命令flutter build apk --target-platform android-arm,android-arm64
不知道和这个有没有关系
@talisk

**Comment by talisk** [comment]
> 这个只是我脚本设置的一个值，和这个没什么关系，因为如果为false那个flutter图标都不会显示。
> 我是使用构建命令flutter build apk --target-platform android-arm,android-arm64
> 不知道和这个有没有关系
> @talisk

@a27919478 问题已经修复，按照 README.md 文档升级到最新版本再试试
