### ISSUE TITLE
Console插件不打印日志

### ISSUE THREAD

**Issue by AIYO77** [bytedance/flutter_ume#5]
## Steps to Reproduce 复现步骤

1. ... 接入UME
2. ... 运行
3. ... Console插件查看日志，空白

**Expected results 期望结果:** Console插件能查看日志输出

**Actual results 实际结果:** Console插件无法查看日志

### Flutter doctor

[✓] Flutter (Channel master, 2.4.0-5.0.pre.145, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)

``` bash

```

### UME and kits version UME 及插件包版本

flutter_ume: ^0.2.0-dev.0
flutter_ume_kit_ui: ^0.2.0-dev.0 # null-safety 版本: ^0.2.0-dev.0
flutter_ume_kit_device: ^0.2.0-dev.0  # null-safety 版本: ^0.2.0-dev.0
flutter_ume_kit_perf: ^0.2.0-dev.0  # null-safety 版本: ^0.2.0-dev.0
flutter_ume_kit_console: ^0.2.0-dev.0  # null-safety 版本: ^0.2.0-dev.0

``` bash

```

**Comment by clevertension** [comment]
贴一下你的代码,你用debugPrint()了吗

**Comment by smileShirely** [comment]
> 贴一下你的代码,你用debugPrint()了吗

是的，辛苦 @masterxing 提供下日志输出的相关代码，目前 UME 仅支持对 `debugPrint` 的收集，开源版暂时无法收集 `print`

**Comment by AIYO77** [comment]
> > 贴一下你的代码,你用debugPrint()了吗
> 
> 是的，辛苦 @masterxing 提供下日志输出的相关代码，目前 UME 仅支持对 `debugPrint` 的收集，开源版暂时无法收集 `print`

好吧，我用的 print
