### ISSUE TITLE
请问有没有计划支持web

### ISSUE THREAD

**Issue by zhongchao** [bytedance/flutter_ume#56]

**Comment by talisk** [comment]
Hi @zhongchao 
web 上已经可以正常使用 flutter_ume。但 web 专有插件确实比较少。
我们正在发起 flutter_ume 的插件开发大赛，欢迎为 flutter_ume 贡献包括且不限于 web 平台的插件功能；详情请见：https://mp.weixin.qq.com/s/RuwiiQAdrGqI00fDhUO77g
