### ISSUE TITLE
能否移除内部的MaterialApp组件

### ISSUE THREAD

**Issue by Laurie-Lin** [bytedance/flutter_ume#6]
如readme所说，我们不得不为弹窗额外添加一个参数，我认为这是侵入性的。
```dart
void runAppWithTool(Widget app) {
  runApp(Directionality(
    child: MediaQuery(
      data: MediaQueryData.fromWindow(window),
      child: Localizations(
        locale: const Locale('en', 'US'),
        delegates: _localizationsDelegates.toList(),
        child: Stack(
          children: [
            app,
            UME(),
          ],
        ),
      ),
    ),
    textDirection: TextDirection.ltr,
  ));
}
```
例如上面的代码同样也能实现UME悬浮组件的显示，或者通过Overlay组件，至少这都不会为我们的app新增加一个路由栈。

**Comment by smileShirely** [comment]
> 如readme所说，我们不得不为弹窗额外添加一个参数，我认为这是侵入性的。
> 
> ```dart
> void runAppWithTool(Widget app) {
>   runApp(Directionality(
>     child: MediaQuery(
>       data: MediaQueryData.fromWindow(window),
>       child: Localizations(
>         locale: const Locale('en', 'US'),
>         delegates: _localizationsDelegates.toList(),
>         child: Stack(
>           children: [
>             app,
>             UME(),
>           ],
>         ),
>       ),
>     ),
>     textDirection: TextDirection.ltr,
>   ));
> }
> ```
> 
> 例如上面的代码同样也能实现UME悬浮组件的显示，或者通过Overlay组件，至少这都不会为我们的app新增加一个路由栈。

@Nightmare-MY 感谢反馈。UME 有考虑对插件层级调整，并移除独立 MaterialApp，这部分调整预期会在下一个大版本实现，还需要一些时间

**Comment by Laurie-Lin** [comment]
期待新版的发布~

**Comment by smileShirely** [comment]
#13 Merged.

修改 pubspec.yaml 中内容：
``` yaml
dependency_overrides:
  flutter_ume:
    git: https://github.com/bytedance/flutter_ume.git
    ref: develop_nullsafety
```

@Nightmare-MY 试一下？

**Comment by Laurie-Lin** [comment]
> #13 Merged.
> 
> 修改 pubspec.yaml 中内容：
> 
> ```yaml
> dependency_overrides:
>   flutter_ume:
>     git: https://github.com/bytedance/flutter_ume.git
>     ref: develop_nullsafety
> ```
> 
> @Nightmare-MY 试一下？

好的~

**Comment by smileShirely** [comment]
@Nightmare-MY 请问针对本 Issue 还有什么问题吗

**Comment by Laurie-Lin** [comment]
> @Nightmare-MY 请问针对本 Issue 还有什么问题吗

没有了哦，感谢支持~
