### ISSUE TITLE
1.0.0-dev.0依赖冲突

### ISSUE THREAD

**Issue by SheepYang1993** [bytedance/flutter_ume#61]
Because flutter_ume_kit_dio >=1.0.0-dev.0 depends on flutter_ume ^1.0.0 which doesn't match any versions, flutter_ume_kit_dio >=1.0.0-dev.0 is forbidden.
So, because group_chat depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.
pub get failed (1; So, because group_chat depends on flutter_ume_kit_dio ^1.0.0-dev.0, version solving failed.)

**Comment by Unicellular-SU** [comment]
可以暂时通过覆盖的方式解决
`dependency_overrides: 
    flutter_ume: ^1.0.0-dev.0`

**Comment by talisk** [comment]
@SheepYang1993 @Unicellular-SU 

`1.0.0` 正式版本已经发布，现在不通过覆盖版本也可以使用了。

**Comment by talisk** [comment]
@SheepYang1993 @Unicellular-SU 

`1.0.0` 正式版本已经发布，现在不通过覆盖版本也可以使用了。
