### ISSUE TITLE
为啥 Dio 工具中展示的网络请求信息要加入 U+200b ？

### ISSUE THREAD

**Issue by Anonymous-fe** [bytedance/flutter_ume#67]
## What's your question 你遇到了什么问题

在 copy dio 请求数据的时候，发现 copy 出来的数据不能被解析，比如 json 无法直接被格式化等等。
看了下代码发现在展示网络请求信息的时候使用了 `\u+200b` 这个不可见字符对字符进行了拼接。

我不太理解这个操作的意图，想问下为啥要这么做

```dart
TextSpan(text: content.notBreak),
...
extension _StringExtension on String {
  String get notBreak => Characters(this).toList().join('\u{200B}');
}
```

## Environmental info 环境信息

不需要

### UME and kits version UME 及插件包版本

flutter_ume_kit_dio 1.0.0

**Comment by talisk** [comment]
@AlexV525

**Comment by AlexV525** [comment]
先前在处理文字的显示时，为了避免文字被过度换行，添加了零宽字符 `\u200b` 进行处理。后续可以去掉进行直出。
