### ISSUE TITLE
Flutter SDK 3.0.5编译报错

### ISSUE THREAD

**Issue by wei-spring** [bytedance/flutter_ume#84]
Flutter SDK 3.0.5
UME:最新版

编译报错，flutter_logo.dart 文件， canvas.transform(Float64List.fromList，Float64List找不到

解决方案：
1、增加导包；
或
用SDK自带的flutter logo,不用再自己copy份，本身SDK里面就有flutter_logo.dart 的

**Comment by hai046** [comment]
我也遇到了，不过我稍微调整了一下引用
```
  #  高版本有问题 先用1.0.1
  flutter_ume: 1.0.1
  flutter_ume_kit_ui: 1.0.0
  flutter_ume_kit_device: 1.0.0
  flutter_ume_kit_perf: 1.0.0
  #  flutter_ume_kit_show_code: 1.0.0
  flutter_ume_kit_console: 1.0.0
```

**Comment by talisk** [comment]
A new version has been published. The 1.1.2 fixed the issue. @hai046 @wei-spring
