### ISSUE TITLE
flutter_ume_kit_console适配第三方日志插件logger问题

### ISSUE THREAD

**Issue by ClarkChu07** [bytedance/flutter_ume#86]
使用第三方日志插件代码如下：
`
import 'package:logger/logger.dart';

// 统一日志打印配置
var logger = Logger(
  printer: PrettyPrinter(
    methodCount: 2, // number of method calls to be displayed
    errorMethodCount: 8, // number of method calls if stacktrace is provided
    lineLength: 120, // width of the output
    colors: true, // Colorful log messages
    printEmojis: true, // Print an emoji for each log message
    printTime: true // Should each log print contain a timestamp
  ),
);

`

发现flutter_ume无法打印出日志

**Comment by hai046** [comment]
我当时也遇到了， 后来我看了一下，需要使用/使用debugPrint 代替print
```
class XXXXConsoleOutput extends LogOutput {
  @override
  void output(OutputEvent event) {
    final msg = event.lines.join('\n');
    //使用debugPrint 代替print
    debugPrint(msg);
   
  }
```

**Comment by talisk** [comment]
暂无计划适配。欢迎提交 Pull Request 来支持更多日志工具

**Comment by CCXXXI** [comment]
> 使用 debugPrint 代替print

也可以用

```dart
ConsoleManager.streamController!.add("message");
```

这样相比 `debugPrint` 有两个好处：

- 如果已经用了其他方式把日志打印到终端，可以避免重复打印
- 在非 debug 模式下也能使用

另外，根据

https://github.com/bytedance/flutter_ume/blob/de91a3605f66a45064bd6890c37d8b0aafef7535/kits/flutter_ume_kit_console/lib/console/console_manager.dart#L16

https://github.com/bytedance/flutter_ume/blob/de91a3605f66a45064bd6890c37d8b0aafef7535/kits/flutter_ume_kit_console/lib/console/console_manager.dart#L20-L43

可以知道尽管接口被设计为 `StreamController?`，但拿到的 `ConsoleManager.streamController` 不会是 `null`
