### ISSUE TITLE
no versions of flutter_ume_kit_perf match >1.0.0 <2.0.0

### ISSUE THREAD

**Issue by SheepYang1993** [bytedance/flutter_ume#99]
Because no versions of flutter_ume_kit_perf match >1.0.0 <2.0.0 and flutter_ume_kit_perf 1.0.0 depends on vm_service ^7.1.1, flutter_ume_kit_perf ^1.0.0 requires vm_service ^7.1.1.
And because flutter_ume >=1.1.1+1 depends on vm_service ^9.4.0, flutter_ume_kit_perf ^1.0.0 is incompatible with flutter_ume >=1.1.1+1.

**Comment by talisk** [comment]
@SheepYang1993 You can add version constraints in dependency_overrides of pubspec.yaml.
